name: CI

on:
  push:
    paths:
      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: npm install, build
        run: |
          npm install
          npm run compile
          npm run package
